name: CI-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    name: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.buildtype }}-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, macos-clang, windows-msvc]
        buildtype: [Debug, Release]
        include:
          - name: windows-msvc
            os: windows-latest
            cxx: cl.exe
            cc: cl.exe
            triplet: x64-windows
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            packages: >
              opencl 
          - name: ubuntu-gcc
            os: ubuntu-latest
            cxx: g++
            cc: gcc
            triplet: x64-linux
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            packages: >
              opencl
          - name: ubuntu-clang
            os: ubuntu-latest
            cxx: clang++
            cc: clang
            triplet: x64-linux
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            packages: >
              opencl
          - name: macos-clang
            os: macos-latest
            cxx: clang++
            cc: clang
            triplet: x64-osx
            vcpkgCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
            packages: >
              opencl

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install cmake v3.20.1
        uses: lukka/get-cmake@v3.20.1     
      
      - name: Install packages [vcpkg]
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          runVcpkgInstall: true
          # vcpkgArguments: ${{ matrix.packages }}
          # vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'
          appendedCacheKey: vcpkginstall
          #vcpkgGitCommitId: cdd51899f6ae3736bfbe936f9e387f86d4a63a58 #ec6fe06e8da05a8157dc8581fa96b36b571c1bd5 

      - name: Configure and Build [Cmake]
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          runVcpkgEnvFormatString: true
          


