name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
      - name: git checkout repository
        uses: actions/checkout@v3

      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: "13"
