name: CI-Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ closed ]

jobs:

  build:
    
    name: ${{ matrix.os }}-${{ matrix.cxx }}-${{ matrix.buildtype }}-test-coverage
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        name: [macos-clang]
        buildtype: [Debug]
        include:
          - name: macos-clang
            os: macos-latest
            cxx: clang++
            cc: clang
            triplet: x64-osx
            packages: >
              python3 opencl

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Set Environment vars
        run: |
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
      
      - name: Run vcpkg
        uses: lukka/run-vcpkg@main
        with:
          vcpkgArguments: ${{ matrix.packages }}
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5 #7db401cb1ef1fc559ec9f9ce814d064c328fd767  
          
      # - name: Run CMake with Ninja
      #   uses: lukka/run-cmake@main
      #   id: runcmake
      #   with:
      #     buildDirectory: ${{ runner.workspace }}/build
      #     cmakeBuildType: ${{ matrix.buildtype }}
      #     cmakeGenerator: 'Ninja'  
      #     cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      #     cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
      #     useVcpkgToolchainFile: true
      #     buildWithCMakeArgs: '-- -v'
      #     cmakeAppendedArgs: '-DBUILD_CODE_COVERAGE=ON'

      - name: Run CMake
        shell: bash
        run: |
          cmake -S ${{ github.workspace }} -B ${{ runner.workspace }}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_CODE_COVERAGE=ON
          cd ${{ runner.workspace }}/build && make

      - name: Run Coverage analysis
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cd ${{ runner.workspace }}/build
          make coverage_xml

      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ${{ runner.workspace }}/build/coverage_xml.xml
          name: CLIc_coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
